export const ACTION_TYPE = {
	SET_TASKS: 'SET_TASKS',
	SET_ORDER_COLUMN: 'SET_ORDER_COLUMN',
	SET_SEARCH_TERM: 'SET_SEARCH_TERM',
	SET_LOADING_STATUS: 'SET_LOADING_STATUS',
	SET_CREATING_STATUS: 'SET_CREATING_STATUS',
	SET_DELETING_STATUS: 'SET_DELETING_STATUS',
	SET_UPDATING_STATUS: 'SET_UPDATING_STATUS',
	SET_SEARCHING_STATUS: 'SET_SEARCHING_STATUS',
}
